### ISSUE TITLE
is it possible to feed images with different height and width as input into network directly?

### ISSUE THREAD

**Issue by BackT0TheFuture** [anayebi/keras-extra#10]
Hi,
   I am new to Keras and ML . Now I am trying to do some tests about OCR via CNN+LSTM or just LSTM. after searching connect CNN with RNN I found **keras-extra** . Currently I have hundreds of images and the corresponding words (ground truth). One image can be split into many lines, there should be one word each line at least (demo images as follows). Images after line-segmented may have **different height and width**.  I looked into mnist_cnn.py and mnist_irnn.py, the input is a single letter and images have the same size.  the expected output ( label or ground truth) is encoded as numpy array by its index of charset :

```
digits_letters = u"abcdefghijklmnopqrstuvwxyz"
charset = sorted(list(digits_letters))
"keras" can be encoded as  [10  4 17  0 18] <type 'numpy.ndarray'>
```

 How to set up the model to perform this kind task so that **images with different size can be feed into network directly?**

Any advice will be welcomed. Thanks in advance!
Best regards,

**demo images**
page
![one page](https://cloud.githubusercontent.com/assets/10088733/13815619/44a4dc00-ebc6-11e5-858b-4c0adda947c4.png)
**images after line-segmented**
Line-1  labeled "keras"
![line-1-keras](https://cloud.githubusercontent.com/assets/10088733/13815646/64d12bdc-ebc6-11e5-9dbd-ce72e0026142.png) 
Line-2 labeled "is a" 
![line-2-is a](https://cloud.githubusercontent.com/assets/10088733/13815660/6c8d72ea-ebc6-11e5-8dd2-2607680e8830.png)
Line-3 labeled "great"
![line-3-great](https://cloud.githubusercontent.com/assets/10088733/13815668/77641f2a-ebc6-11e5-8cfa-c2a58b079814.png)
Line-4 labeled "tool"
![line-4-tool](https://cloud.githubusercontent.com/assets/10088733/13815704/902f5d26-ebc6-11e5-8916-8e6a02f212ef.png)

**Comment by anayebi** [comment]
No, I don't think it is unless you do some sort of zero padding (perhaps using one of the masking layers in Keras).
