### ISSUE TITLE
Implementation of CNN+  bidirectional LSTM for videos

### ISSUE THREAD

**Issue by dakshvar22** [anayebi/keras-extra#12]
@anayebi 

I have 25 videos of 2710 frames(RGB images of size 32x32) each. So there are 3 channels in each frame. How do I build my model to take in video input(all frames of video at once) for the CNN and further the time step for LSTM would be the number of frames. Here is my code that I have written using the keras extras library - 

`
    model.add(TimeDistributedConvolution2D(32, 3, 3, border_mode='same',input_shape=(2710,2710,img_channels, img_rows, img_cols)))
    model.add(keras.layers.normalization.BatchNormalization())
    model.add(Activation('relu'))
    model.add(TimeDistributedMaxPooling2D(pool_size=(2, 2)))
    model.add(Dropout(0.25))

```
model.add(TimeDistributedConvolution2D(32, 3, 3, border_mode='same'))
# model.add(keras.layers.normalization.BatchNormalization())
model.add(Activation('relu'))
model.add(TimeDistributedMaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))

model.add(TimeDistributedConvolution2D(32, 3, 3, border_mode='same'))
# model.add(keras.layers.normalization.BatchNormalization())
model.add(Activation('relu'))
model.add(TimeDistributedMaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))


model.add(TimeDistributedFlatten())
model.add(LSTM(output_dim=255,return_sequences=True))


model.add(TimeDistributedDense(256,activation='relu'))
model.add(TimeDistributedDense(128,activation='relu'))
# model.add(Dense(512,activation='relu'))

model.add(TimeDistributedDense(1,activation='sigmoid'))

sgd = SGD(lr = 0.1, decay = 1e-5, momentum=0.9, nesterov=True)
model.compile(loss='mean_absolute_error',
          optimizer=sgd,
          metrics=['accuracy'])
```

`

I get this error `
model.add(TimeDistributedConvolution2D(32, 3, 3, border_mode='same',input_shape=(2710,2710,img_channels, img_rows, img_cols)))
  File "build/bdist.linux-x86_64/egg/keras/layers/extra.py", line 89, in __init__
AttributeError: can't set attribute
`

Can you please help me out asap.

**Comment by dakshvar22** [comment]
@anayebi Why have you closed the issue?

**Comment by anayebi** [comment]
Already answered here (putting the link for reference): https://github.com/fchollet/keras/issues/2646#issuecomment-217515350

**Comment by dakshvar22** [comment]
@anayebi  Can you give me the link to Keras 0.3.0?

**Comment by anayebi** [comment]
If you already have Keras 1.0.2 installed, isn't it easier for you to just use the TimeDistributed wrapper on Convolution2D? It ought to do the same thing as TimeDistributedConvolution2D.

**Comment by dakshvar22** [comment]
@anayebi ok i used the exact same example code that you have provided in the README - 
`model.add(TimeDistributed(Convolution2D(8, 4, 4, border_mode='valid', input_shape=(10,1,32,32))))
    model.add(TimeDistributed(MaxPooling2D(pool_size=(2, 2),border_mode='valid')))
    model.add(Activation('relu'))
    model.add(TimeDistributed(Convolution2D(8, 3, 3, border_mode='valid')))
    model.add(Activation('relu'))
    model.add(TimeDistributedFlatten())
    model.add(Activation('relu'))
    model.add(GRU(output_dim=100,return_sequences=True))
    model.add(GRU(output_dim=50,return_sequences=False))
    model.add(Dropout(.2))
    model.add(Dense(1))
`

I still get an error - 

> File "/home/toothless/daksh/ml/project/src/model/model2.py", line 133, in buildModel
>     model.add(TimeDistributed(Convolution2D(8, 4, 4, border_mode='valid', input_shape=(10,1,32,32))))
>   File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 102, in add
>     raise Exception('The first layer in a Sequential model must '
> Exception: The first layer in a Sequential model must get an `input_shape` or `batch_input_shape` argument.

I have added the input_shape argument to the first layer, but still it throws an error. Please help me out.

**Comment by dakshvar22** [comment]
@anayebi  Just to add.. I am getting the following error while building the model itself. I have not used model.fit() still.
