### ISSUE TITLE
keras extra running an example

### ISSUE THREAD

**Issue by afsanehghasemi** [anayebi/keras-extra#2]
Hi,
I am trying to use conv2D plus LSTM to train a network with sequence of images (16 frames) and each sequence has 10 labels.

I made a simulation using Keras.extra and mnist data using the following code,

from **future** import absolute_import
from **future** import print_function
import numpy as np
import pandas as pd  
from random import random
from sklearn.feature_extraction import image
from keras.preprocessing import sequence
from keras.optimizers import SGD, RMSprop, Adagrad
from keras.utils import np_utils
from keras.models import Sequential
from keras.initializations import normal, identity
from keras.layers.core import Dense, Dropout, Activation, Flatten, Permute, Reshape, TimeDistributedDense
from keras.layers.embeddings import Embedding
from keras.layers.recurrent import LSTM, GRU, SimpleRNN
from keras.layers.convolutional import Convolution1D, MaxPooling1D
from keras.layers.convolutional import Convolution2D, MaxPooling2D
# from keras.layers.convolutional.TimeDistributedConvolution2D import TimeDistributedConvolution2

from keras.layers.extra import TimeDistributedConvolution2D, TimeDistributedMaxPooling2D, TimeDistributedFlatten
from keras.layers.recurrent import LSTM
from keras.datasets import mnist

(X_train, y_train), (X_test, y_test) = mnist.load_data()
X_train = X_train.astype('float32')
X_test = X_test.astype('float32')
'-----------------------------------------------Normalization------------------------------------------'
X_train /= 255
X_test /= 255
'-------------------------------------------------convert to the sequence of Images---------------------'
listy = [[] for i in range(16)]
listtr_ = [[] for i in range(16)]
tr_ =  [[] for i in range(100)]
tr_lbl =  [[] for i in range(100)]

for k in range(0,100,1):#number of samples
    listy = [[] for i in range(16)]
    #print(np.shape(listy))
    index = 0
    im = X_train[k]
    lbl = y_train[k]
    windowsize_r = 7
    windowsize_c = 7
    temp = []
    # Crop out the window and calculate the histogram
    for r in range(0,im.shape[0] , windowsize_r):
        for c in range(0,im.shape[1] , windowsize_c):
            window = im[r:r+windowsize_r,c:c+windowsize_c]
            listy[index].append(window)
            temp.append(window)
            listtr_[index].append(lbl);
            index = index + 1

```
tr_[k] = listy
tr_lbl[k] = listtr_
```

'-----------------------------------------------model parameters----------------------------------------'
# lstm

n_hidden = 256
n_samples = 100
n_timesteps = 16
# Convolution

filter_length = 3
# number of convolutional filters to use

nb_filters = 32
# size of pooling area for max pooling

nb_pool = 3
# RNN

hidden_units = 100
nb_classes = 10
learning_rate = 0.1
batch_size = 20
nb_epochs = 100
nb_samples_tr = 100
nb_samples_te = 50
'------------------------------------------------------------------------------------------------------'
model = Sequential()
model.add(TimeDistributedConvolution2D(32, 3, 3, border_mode='same', input_shape=(n_timesteps,1, 7, 7)))
model.add(TimeDistributedMaxPooling2D(pool_size=(nb_pool, nb_pool)))
model.add(Activation('relu'))
model.add(TimeDistributedFlatten())
model.add(LSTM(256, return_sequences=True))
model.add(TimeDistributedDense(nb_classes))
model.add(Activation('softmax'))

rmsprop = RMSprop(lr=learning_rate)
model.compile(loss='categorical_crossentropy', optimizer=rmsprop)
tr_lbl = np.random.randn(100,10)
print('input shape:')
print(np.shape(tr_))
print('target shape:')
print(np.shape(tr_lbl))
model.fit(tr_, tr_lbl, batch_size=100, nb_epoch=10)
'----------------------------------------------------------------------------------------------

However, I still get stock on running the network properly. Here is the error I have received,

input shape:
(100, 16, 1, 7, 7)
target shape:
(100, 10)
Traceback (most recent call last):
  File "myLSTM.py", line 169, in <module>
    model.fit(tr_, tr_lbl, batch_size=100, nb_epoch=10)
  File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 503, in fit
    raise Exception('All input arrays and the target array must '
Exception: All input arrays and the target array must have the same number of samples.

**Comment by anayebi** [comment]
If your output is (100, 10), then that is incorrect. You must have the extra dimension of time as your output since you have the return_sequences flag set to True. So assuming the number of timesteps is t, then your output shape should be of the form (100, t, 10).

Also, if you have 16 frames, then your input shape needs to be (100, 1, 16, 7, 7), as I am assuming the number of timesteps is 1 for you (from what I interpret).

**Comment by badripatro** [comment]
Is this function  "TimeDistributedConvolution2D() "  or similar to this function available in torch. how will I implement this API in the torch.
