### ISSUE TITLE
Extra module ImportError

### ISSUE THREAD

**Issue by wtlim** [anayebi/keras-extra#3]
Hi, @anayebi . 
I'm trying to use your 'keras-extra' to build a lrcn network.
I installed 'keras-extra' following your README instruction.
Unfortunately, It returns an error message as below.

from keras.layers.extra import TimeDistributedConvolution2D
ImportError: No module named extra

A "extra.py" file is already in 'keras/layers/' folder and auto complete function properly works
when writing the "from keras.layers.extra import layername"  in Pycharm.

Could you give a suggestion to solve it?
Thx!!

**Comment by anayebi** [comment]
Hi,

I updated the installation instructions in the ReadMe to be more clear. Feel free to try it again, and let me know if it doesn't work for you. :)

**Comment by wtlim** [comment]
Thank you for your comment!
I solved an error according to this page.(so simple...)
http://stackoverflow.com/questions/28705029/pycharm-error-no-module-when-trying-to-import-own-module-python-script

[Summary]
1. PyCharm, Run -> Edit Configurations
2. Uncheck both "Add content roots to PYTHONPATH" and "Add source roots to PYTHONPATH". 

Now it seems to be working fine :)

**Comment by amir-abdi** [comment]
I am facing the same problem with pycharm.
While running python in command line recognizes keras.layers.extra, in pycharm I receive the error: 'No module named 'keras.layers.extra'

The weird part is that the IDE intellisence recognises this module and auto complete works, but when running the project, I received the above error.

@wtlim 's suggestion did not work
