### ISSUE TITLE
Keras 3.1

### ISSUE THREAD

**Issue by AntreasAntoniou** [anayebi/keras-extra#4]
Hey man,

Is this supported in Keras 3.1? I get the following error:

`Exception                                 Traceback (most recent call last)
/usr/lib/python2.7/dist-packages/IPython/utils/py3compat.pyc in execfile(fname, *where)
    202             else:
    203                 filename = fname
--> 204             **builtin**.execfile(filename, *where)

/home/ubuntumax/keras_branch/keras-dsb/experiment.py in <module>()
    304             create(sys.argv[2])
    305         elif sys.argv[1] == 'run':
--> 306             run(sys.argv[2])
    307         elif sys.argv[1] == 'continue':
    308             run(sys.argv[2], cont=True)

/home/ubuntumax/keras_branch/keras-dsb/experiment.py in run(experiment_name, cont)
     59     print('Loading models...')
     60     model_module = import_module(experiment_path, MODEL_PY)
---> 61     model_systole = model_module.get_model()
     62     model_diastole = model_module.get_model()
     63     # save model to JSON

/home/ubuntumax/keras_branch/keras-dsb/experiments/VGG_Time_Distributed_LSTM/model.pyc in get_model()
     20 def get_model():
     21     conv = Sequential()
---> 22     conv.add(Activation(activation=scale, input_shape=(30, 1, 128, 128)))
     23     conv.add(TimeDistributedConvolution2D(64, 3, 3, border_mode='same'))
     24     conv.add(Activation('relu'))

/usr/local/lib/python2.7/dist-packages/keras/layers/core.pyc in **init**(self, activation, **kwargs)
    652     '''
    653     def **init**(self, activation, **kwargs):
--> 654         super(Activation, self).**init**(**kwargs)
    655         self.activation = activations.get(activation)
    656 

/usr/local/lib/python2.7/dist-packages/keras/layers/core.pyc in **init**(self, **kwargs)
     41             assert kwarg in allowed_kwargs, 'Keyword argument not understood: ' + kwarg
     42         if 'input_shape' in kwargs:
---> 43             self.set_input_shape((None,) + tuple(kwargs['input_shape']))
     44         if 'batch_input_shape' in kwargs:
     45             self.set_input_shape(tuple(kwargs['batch_input_shape']))

/usr/local/lib/python2.7/dist-packages/keras/layers/core.pyc in set_input_shape(self, input_shape)
    138                                 ', was provided with input shape ' + str(input_shape))
    139         self._input_shape = input_shape
--> 140         self.input = K.placeholder(shape=self._input_shape)
    141         self.build()
    142 

/usr/local/lib/python2.7/dist-packages/keras/backend/theano_backend.pyc in placeholder(shape, ndim, dtype, name)
     53         return T.tensor4(name=name, dtype=dtype)
     54     else:
---> 55         raise Exception('ndim too large: ' + str(ndim))
     56 
     57 

Exception: ndim too large: 5
`

My actual code:

`conv = Sequential()
    conv.add(Activation(activation=scale, input_shape=(30, 1, 128, 128)))
    conv.add(TimeDistributedConvolution2D(64, 3, 3, border_mode='same'))
    conv.add(Activation('relu'))
    # model.add(TimeDistributedConvolution2D(64, 3, 3))
    # model.add(Activation('relu'))
    conv.add(TimeDistributedMaxPooling2D(pool_size=(2, 2)))
    conv.add(TimeDistributedConvolution2D(128, 3, 3, border_mode='same'))
    conv.add(Activation('relu'))
    # model.add(TimeDistributedConvolution2D(128, 3, 3))
    # model.add(Activation('relu'))
    conv.add(TimeDistributedMaxPooling2D(pool_size=(2, 2)))
    conv.add(TimeDistributedConvolution2D(256, 3, 3, border_mode='same'))
    conv.add(Activation('relu'))
    # model.add(TimeDistributedConvolution2D(256, 3, 3))
    # model.add(Activation('relu'))
    conv.add(TimeDistributedMaxPooling2D(pool_size=(2, 2)))
    conv.add(TimeDistributedConvolution2D(512, 3, 3, border_mode='same'))
    conv.add(Activation('relu'))
    # model.add(TimeDistributedConvolution2D(512, 3, 3))
    # model.add(Activation('relu'))
    conv.add(TimeDistributedMaxPooling2D(pool_size=(2, 2)))
    conv.add(Activation('relu'))
    conv.add(TimeDistributedConvolution2D(512, 3, 3, border_mode='same'))
    conv.add(Activation('relu'))
    # model.add(TimeDistributedConvolution2D(512, 3, 3))
    # model.add(Activation('relu'))
    conv.add(TimeDistributedMaxPooling2D(pool_size=(2, 2)))
    conv.add(Activation('relu'))
    conv.add(TimeDistributedConvolution2D(512, 3, 3, border_mode='same'))
    conv.add(Activation('relu'))
    # model.add(TimeDistributedConvolution2D(512, 3, 3))
    # model.add(Activation('relu'))
    conv.add(TimeDistributedMaxPooling2D(pool_size=(2, 2)))
    conv.add(Activation('relu'))
    # model.add(TimeDistributedConvolution2D(512, 3, 3, border_mode='same'))
    # model.add(Activation('relu'))
    # # model.add(TimeDistributedConvolution2D(512, 3, 3))
    # # model.add(Activation('relu'))
    # model.add(TimeDistributedMaxPooling2D(pool_size=(2, 2)))
    # model.add(Activation('relu'))
    # model.add(TimeDistributedConvolution2D(512, 3, 3, border_mode='same'))
    # model.add(Activation('relu'))
    # # model.add(TimeDistributedConvolution2D(512, 3, 3))
    # # model.add(Activation('relu'))
    # model.add(TimeDistributedMaxPooling2D(pool_size=(2, 2)))
    # model.add(Activation('relu'))
    conv.add(TimeDistributedFlatten())
    conv.add(LSTM(512, return_sequences=True))
    conv.add(Dropout(0.5))
    conv.add(Dense(1))`

**Comment by anayebi** [comment]
Thanks for the notification! 
I can only guarantee support for Keras 0.3.0, not 0.3.1. If you downgrade to 0.3.0, then it should work fine (and you shouldn't get the error the ndim = 5 is too large).

Hope that helps,
Aran
