### ISSUE TITLE
load model issue

### ISSUE THREAD

**Issue by XuesongYang** [anayebi/keras-extra#9]
load model issue as follows. Any suggestions? Thanks

   model = model_from_json(json_str) 
  File keras/models.py, line 166, in model_from_json
    return model_from_config(config, custom_objects=custom_objects)
  File "keras/models.py", line 177, in model_from_config
    model = container_from_config(config, custom_objects=custom_objects)
  File "keras/utils/layer_utils.py", line 57, in container_from_config
    layer = container_from_config(layer_dict['nodes'].get(node['name']))
  File "keras/utils/layer_utils.py", line 92, in container_from_config
    base_layer = get_layer(name, layer_dict)
  File "keras/utils/layer_utils.py", line 158, in get_layer
    instantiate=True, kwargs=kwargs)
  File "keras/utils/generic_utils.py", line 14, in get_from_module
    str(identifier))
Exception: Invalid layer: TimeDistributedConvolution2D

**Comment by XuesongYang** [comment]
I find the solution, please close it.

add `from .extra import *` in file `keras/layers/__init__.py`, and then

`model = model_from_json(json_str, custom_objects={'TimeDistributedConvolution2D': TimeDistributedConvolution2D, 'TimeDistributedFlatten': TimeDistributedFlatten, 'TimeDistributedMaxPooling2D': TimeDistributedMaxPooling2D})`

**Comment by anayebi** [comment]
Sounds good, thanks for looking into this!
